package cjd.love.hqy.hr.pojo.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWorkScheduling<M extends BaseWorkScheduling<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setWorkMan(java.lang.Integer workMan) {
		set("work_man", workMan);
	}

	public java.lang.Integer getWorkMan() {
		return get("work_man");
	}

	public void setWorkManName(java.lang.String workManName) {
		set("work_man_name", workManName);
	}

	public java.lang.String getWorkManName() {
		return get("work_man_name");
	}

	public void setWorkDate(java.util.Date workDate) {
		set("work_date", workDate);
	}

	public java.util.Date getWorkDate() {
		return get("work_date");
	}

	public void setCreatedDate(java.util.Date createdDate) {
		set("created_date", createdDate);
	}

	public java.util.Date getCreatedDate() {
		return get("created_date");
	}

}
