package cjd.love.hqy.hr.pojo;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_employee", "id", Employee.class);
		arp.addMapping("t_judgement", "id", Judgement.class);
		arp.addMapping("t_leave", "id", Leave.class);
		arp.addMapping("t_work_scheduling", "id", WorkScheduling.class);
	}
}

