package cjd.love.hqy.hr.pojo;

import cjd.love.hqy.hr.pojo.base.BaseEmployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Employee extends BaseEmployee<Employee> {
	public static final Employee dao = new Employee();
}
