package cjd.love.hqy.hr.pojo;

import cjd.love.hqy.hr.pojo.base.BaseJudgement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Judgement extends BaseJudgement<Judgement> {
	public static final Judgement dao = new Judgement();
}
