package cjd.love.hqy.hr.pojo;

import cjd.love.hqy.hr.pojo.base.BaseLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Leave extends BaseLeave<Leave> {
	public static final Leave dao = new Leave();
}
