package cjd.love.hqy.hr.pojo;

import cjd.love.hqy.hr.pojo.base.BaseWorkScheduling;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WorkScheduling extends BaseWorkScheduling<WorkScheduling> {
	public static final WorkScheduling dao = new WorkScheduling();
}
